idf_component_register(
    SRCS
        "adc_scope_test.c"
        "app.c"
        "device_configuration.c"
        "recording_controller.c"
        "task_acquisition.c"
        "task_bluetooth.c"
        "task_communication.c"
        "task_processing.c"
        "task_storage.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        common
    PRIV_REQUIRES
        data_format
        esp32s3_devkit
        freertos
        rev_1
        magnetic
        protocol
        transports
)
