idf_component_register(
    SRCS
        "src/platform_gpio.c"
        "src/platform_spi.c"
        "src/platform_time.c"
        "src/platform_uart.c"
    INCLUDE_DIRS
        "include"
    REQUIRES
        common
    PRIV_REQUIRES
        esp_driver_gpio
        esp_driver_spi
        esp_driver_uart
        esp_timer
        freertos
        heap
)
