#ifndef GEOPHYS_BOARD_REV_1_CONFIG_H
#define GEOPHYS_BOARD_REV_1_CONFIG_H

#include <stdbool.h>
#include <stdint.h>

#include "platform_gpio.h"
#include "platform_spi.h"
#include "platform_uart.h"

/* Direct ESP32-S3 GPIO assignments. */
#define BOARD_REV1_GPIO_SOLAR_PRESENT          UINT32_C(1)
#define BOARD_REV1_GPIO_USB_5V_PRESENT         UINT32_C(2)
#define BOARD_REV1_GPIO_DEVICE_DETECT_1        UINT32_C(3)
#define BOARD_REV1_GPIO_SD_D1                  UINT32_C(4)
#define BOARD_REV1_GPIO_SD_D0                  UINT32_C(5)
#define BOARD_REV1_GPIO_SD_D3                  UINT32_C(6)
#define BOARD_REV1_GPIO_SD_CLOCK               UINT32_C(7)
#define BOARD_REV1_GPIO_DEVICE_DETECT_2        UINT32_C(8)
#define BOARD_REV1_GPIO_IMU_MISO               UINT32_C(9)
#define BOARD_REV1_GPIO_ADC_DRDY                UINT32_C(10)
#define BOARD_REV1_GPIO_ADC_CS                  UINT32_C(11)
#define BOARD_REV1_GPIO_ADC_SCLK                UINT32_C(12)
#define BOARD_REV1_GPIO_ADC_MOSI                UINT32_C(13)
#define BOARD_REV1_GPIO_ADC_MISO                UINT32_C(14)
#define BOARD_REV1_GPIO_SD_D2                  UINT32_C(15)
#define BOARD_REV1_GPIO_SD_CMD                 UINT32_C(16)
#define BOARD_REV1_GPIO_IMU_SCLK               UINT32_C(17)
#define BOARD_REV1_GPIO_IMU_MOSI               UINT32_C(18)
#define BOARD_REV1_GPIO_SR_SHIFT_CLOCK         UINT32_C(19)
#define BOARD_REV1_GPIO_SR_STORAGE_CLOCK       UINT32_C(20)
#define BOARD_REV1_GPIO_SR_OUTPUT_ENABLE_N     UINT32_C(21)
#define BOARD_REV1_GPIO_CARD_2_IO_1            UINT32_C(38)
#define BOARD_REV1_GPIO_CARD_2_IO_2            UINT32_C(39)
#define BOARD_REV1_GPIO_CARD_1_IO_1            UINT32_C(40)
#define BOARD_REV1_GPIO_CARD_1_IO_2            UINT32_C(41)
#define BOARD_REV1_GPIO_SUPERCAP_CHARGE_ENABLE UINT32_C(42)
#define BOARD_REV1_GPIO_HOST_UART_TX           UINT32_C(43)
#define BOARD_REV1_GPIO_HOST_UART_RX           UINT32_C(44)
#define BOARD_REV1_GPIO_GNSS_UART_RX           UINT32_C(45)
#define BOARD_REV1_GPIO_IMU_CS                 UINT32_C(46)
#define BOARD_REV1_GPIO_SR_SERIAL_DATA         UINT32_C(47)
#define BOARD_REV1_GPIO_GNSS_UART_TX           UINT32_C(48)

/* Direct-signal active and safe levels. */
#define BOARD_REV1_ADC_DRDY_ACTIVE_LEVEL       PLATFORM_GPIO_LEVEL_LOW
#define BOARD_REV1_ADC_CS_ACTIVE_LEVEL         PLATFORM_GPIO_LEVEL_LOW
#define BOARD_REV1_ADC_CS_SAFE_LEVEL           PLATFORM_GPIO_LEVEL_HIGH
#define BOARD_REV1_IMU_CS_ACTIVE_LEVEL         PLATFORM_GPIO_LEVEL_LOW
#define BOARD_REV1_IMU_CS_SAFE_LEVEL           PLATFORM_GPIO_LEVEL_HIGH
#define BOARD_REV1_SR_SHIFT_ACTIVE_EDGE_LEVEL  PLATFORM_GPIO_LEVEL_HIGH
#define BOARD_REV1_SR_SHIFT_SAFE_LEVEL         PLATFORM_GPIO_LEVEL_LOW
#define BOARD_REV1_SR_STORAGE_ACTIVE_EDGE_LEVEL PLATFORM_GPIO_LEVEL_HIGH
#define BOARD_REV1_SR_STORAGE_SAFE_LEVEL       PLATFORM_GPIO_LEVEL_LOW
#define BOARD_REV1_SR_DATA_SAFE_LEVEL          PLATFORM_GPIO_LEVEL_LOW
#define BOARD_REV1_SR_OUTPUT_ENABLE_LEVEL      PLATFORM_GPIO_LEVEL_LOW
#define BOARD_REV1_SR_OUTPUT_DISABLE_LEVEL     PLATFORM_GPIO_LEVEL_HIGH
#define BOARD_REV1_SOLAR_PRESENT_ACTIVE_LEVEL  PLATFORM_GPIO_LEVEL_LOW
#define BOARD_REV1_USB_5V_PRESENT_ACTIVE_LEVEL PLATFORM_GPIO_LEVEL_LOW

/*
 * GPIO42 has no resolved active or safe driven level. It must remain an input
 * (high impedance) until the board contract is updated from bench evidence.
 */
#define BOARD_REV1_SUPERCAP_CHARGE_DRIVE_ALLOWED false

/* Peripheral assignments and resolved bus limits. */
#define BOARD_REV1_ADC_SPI_HOST                 PLATFORM_SPI_HOST_2
#define BOARD_REV1_ADC_SPI_MODE                 UINT8_C(0)
#define BOARD_REV1_ADC_SPI_BIT_ORDER            PLATFORM_SPI_BIT_ORDER_MSB_FIRST
#define BOARD_REV1_ADC_SPI_INITIAL_CLOCK_HZ     UINT32_C(8000000)
#define BOARD_REV1_ADC_SPI_MAX_READ_CLOCK_HZ    UINT32_C(20000000)
#define BOARD_REV1_ADC_SPI_MAX_WRITE_CLOCK_HZ   UINT32_C(30000000)
#define BOARD_REV1_ADC_SPI_CS_SETUP_US          UINT32_C(1)
#define BOARD_REV1_ADC_SPI_CS_HOLD_US           UINT32_C(1)
#define BOARD_REV1_ADC_SPI_DMA_ENABLED          true
#define BOARD_REV1_ADC_MCLK_HZ                   UINT32_C(8192000)

#define BOARD_REV1_IMU_SPI_HOST                 PLATFORM_SPI_HOST_3
#define BOARD_REV1_IMU_SPI_MAX_CLOCK_HZ         UINT32_C(10000000)

#define BOARD_REV1_HOST_UART_PORT               PLATFORM_UART_PORT_0
#define BOARD_REV1_HOST_UART_DEFAULT_BAUD       UINT32_C(921600)
#define BOARD_REV1_HOST_UART_DATA_BITS          PLATFORM_UART_DATA_BITS_8
#define BOARD_REV1_HOST_UART_PARITY             PLATFORM_UART_PARITY_NONE
#define BOARD_REV1_HOST_UART_STOP_BITS          PLATFORM_UART_STOP_BITS_1
#define BOARD_REV1_GNSS_UART_PORT               PLATFORM_UART_PORT_1
#define BOARD_REV1_GNSS_UART_TARGET_BAUD        UINT32_C(921600)

#define BOARD_REV1_CARD_1_I2C_CONTROLLER        UINT8_C(0)
#define BOARD_REV1_CARD_2_I2C_CONTROLLER        UINT8_C(1)
#define BOARD_REV1_CARD_IO_I2C_INITIALIZATION_ALLOWED false

/* Zero means unresolved and therefore unavailable for initialization. */
#define BOARD_REV1_CARD_I2C_CLOCK_HZ            UINT32_C(0)
#define BOARD_REV1_SDMMC_CLOCK_HZ               UINT32_C(0)

/*
 * U1 and U2 are 74HC595D devices powered at 3.3 V. A 1 us software edge delay
 * stays far below the datasheet's 4 MHz guaranteed floor at 2 V and 125 C.
 */
#define BOARD_REV1_SR_EDGE_DELAY_US              UINT32_C(1)
#define BOARD_REV1_SR_CONSERVATIVE_MAX_CLOCK_HZ UINT32_C(4000000)
#define BOARD_REV1_SR_INSTANCE                  UINT32_C(0)

/* Daisy-chain image: SH1_A..H are bits 15..8; SH2_A..H are bits 7..0. */
typedef enum {
    BOARD_REV1_SHIFT_SET_1 = 0,
    BOARD_REV1_SHIFT_RESET_1 = 1,
    BOARD_REV1_SHIFT_ADC_CONVST_SAR = 2,
    BOARD_REV1_SHIFT_ADC_MCLK_ENABLE = 3,
    BOARD_REV1_SHIFT_ADC_START = 4,
    BOARD_REV1_SHIFT_ADC_RESET = 5,
    BOARD_REV1_SHIFT_SET_2 = 6,
    BOARD_REV1_SHIFT_RESET_2 = 7,
    BOARD_REV1_SHIFT_LED_ENABLE = 8,
    BOARD_REV1_SHIFT_SD_MUX_ENABLE_N = 9,
    BOARD_REV1_SHIFT_USB2641_RESET_N = 10,
    BOARD_REV1_SHIFT_NEGATIVE_5V_ENABLE = 11,
    BOARD_REV1_SHIFT_18V_ENABLE = 12,
    BOARD_REV1_SHIFT_10V_ENABLE = 13,
    BOARD_REV1_SHIFT_3V3A_ENABLE = 14,
    BOARD_REV1_SHIFT_SD_MUX_SELECT = 15,
} board_rev1_shift_output_t;

#define BOARD_REV1_SHIFT_MASK(output_) \
    ((uint16_t)(UINT16_C(1) << (uint8_t)(output_)))

/* Resolved shift-output active levels and required safe levels. */
#define BOARD_REV1_SD_MUX_ESP32_LEVEL            false
#define BOARD_REV1_SD_MUX_USB2641_LEVEL          true
#define BOARD_REV1_3V3A_ENABLE_ACTIVE_LEVEL      true
#define BOARD_REV1_3V3A_ENABLE_SAFE_LEVEL        false
#define BOARD_REV1_10V_ENABLE_ACTIVE_LEVEL       true
#define BOARD_REV1_10V_ENABLE_SAFE_LEVEL         false
#define BOARD_REV1_18V_ENABLE_ACTIVE_LEVEL       true
#define BOARD_REV1_18V_ENABLE_SAFE_LEVEL         false
#define BOARD_REV1_NEGATIVE_5V_ENABLE_ACTIVE_LEVEL true
#define BOARD_REV1_NEGATIVE_5V_ENABLE_SAFE_LEVEL false
#define BOARD_REV1_USB2641_RESET_ACTIVE_LEVEL    false
#define BOARD_REV1_USB2641_RESET_SAFE_LEVEL      false
#define BOARD_REV1_SD_MUX_ENABLE_ACTIVE_LEVEL    false
#define BOARD_REV1_SD_MUX_ENABLE_SAFE_LEVEL      false
#define BOARD_REV1_LED_ENABLE_ACTIVE_LEVEL       true
#define BOARD_REV1_LED_ENABLE_SAFE_LEVEL         false
#define BOARD_REV1_SET_RESET_ACTIVE_LEVEL        true
#define BOARD_REV1_SET_RESET_SAFE_LEVEL          false
#define BOARD_REV1_ADC_RESET_ACTIVE_LEVEL        false
#define BOARD_REV1_ADC_RESET_SAFE_LEVEL          false
#define BOARD_REV1_ADC_START_ACTIVE_LEVEL        false
#define BOARD_REV1_ADC_START_SAFE_LEVEL          true
#define BOARD_REV1_ADC_MCLK_ENABLE_ACTIVE_LEVEL  true
#define BOARD_REV1_ADC_MCLK_ENABLE_SAFE_LEVEL    false
#define BOARD_REV1_ADC_CONVST_ACTIVE_LEVEL       true
#define BOARD_REV1_ADC_CONVST_SAFE_LEVEL         false

#define BOARD_REV1_SHIFT_SAFE_IMAGE              UINT16_C(0x0010)
#define BOARD_REV1_SHIFT_FIXED_LOW_MASK          UINT16_C(0x8600)
#define BOARD_REV1_SHIFT_POWER_RAIL_MASK         UINT16_C(0x7800)
#define BOARD_REV1_SHIFT_SET_RESET_MASK          UINT16_C(0x00C3)

/* Resolved board timing values. */
#define BOARD_REV1_POWER_RAIL_SETTLING_MS        UINT32_C(100)
#define BOARD_REV1_ADC_MCLK_SETTLING_US          UINT32_C(5000)
#define BOARD_REV1_ADC_RESET_ASSERT_US           UINT32_C(2000)
#define BOARD_REV1_ADC_RESET_RELEASE_US          UINT32_C(10000)
#define BOARD_REV1_ADC_SOFT_RESET_SETTLING_US    UINT32_C(5000)
#define BOARD_REV1_ADC_INIT_TIMEOUT_US           UINT32_C(500000)
#define BOARD_REV1_PULSE_RAIL_SETTLING_MS        UINT32_C(100)
#define BOARD_REV1_SET_RESET_PULSE_US            UINT32_C(200)

#define BOARD_REV1_CARD_DETECT_SAMPLE_RATE_HZ    UINT32_C(100)
#define BOARD_REV1_CARD_DETECT_WINDOW_MS         UINT32_C(2000)
#define BOARD_REV1_CARD_DETECT_NO_CARD_MIN_MV    UINT32_C(2750)
#define BOARD_REV1_CARD_DETECT_MAGNETIC_MIN_MV   UINT32_C(1925)
#define BOARD_REV1_CARD_DETECT_MAGNETIC_MAX_MV   UINT32_C(2750)
#define BOARD_REV1_CARD_DETECT_ACCEL_MIN_MV      UINT32_C(1375)
#define BOARD_REV1_CARD_DETECT_ACCEL_MAX_MV      UINT32_C(1925)
#define BOARD_REV1_CARD_DETECT_RESISTIVITY_MIN_MV UINT32_C(550)
#define BOARD_REV1_CARD_DETECT_RESISTIVITY_MAX_MV UINT32_C(1375)

#endif /* GEOPHYS_BOARD_REV_1_CONFIG_H */
